source 'https://github.com/CocoaPods/Specs.git'
target 'FinalProject' do
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FirebaseUI/Twitter'
pod 'FirebaseUI/Phone'

end
