source 'https://github.com/CocoaPods/Specs.git'
target 'FinalProject' do
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacesAPI'
pod 'Alamofire', '~> 4'
pod 'SwiftyJSON'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Storage'
pod 'ViewRow', :git => 'https://github.com/EurekaCommunity/ViewRow'
pod 'FirebaseUI/Twitter'
pod 'FirebaseUI/Phone'
pod 'GaugeKit'
pod 'AlamofireNetworkActivityIndicator'
pod 'Firebase/Database'
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if  target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
pod 'ImageRow', '~> 3.0'
end
